### PR TITLE
Allows usage of UV, CPython and pypy mirrors

### LINKED ISSUE #146: Allow usage of UV, CPython and pypy mirrors
First let me thank you again for this wonderful tool!

## Context
We want to use **pyapp** in order to make easier the deployment and installation of some of ours **CI/CD** python tools.
However, depending on the environments, sometimes the **connection to the public internet is closed**. We want to be able to target our own mirrors, for which we have an network connectivity. These mirrors are proxying known external providers, including GitHub, and caching stuff.

Example: https://jfrog.com/help/r/jfrog-artifactory-documentation/configure-vcs-repository-layout

Currently, if you do not hardcode a specific distribution file URL with `PYAPP_DISTRIBUTION_SOURCE`, **pyapp** will always download UV, CPython and Pypy from their official source:
- https://github.com/astral-sh/uv
- https://github.com/indygreg/python-build-standalone
- https://downloads.python.org/pypy

I think this is issue can really be a blocker-point in large companies.
In fact, I want to promote pyapp as much as possible in my company and this is a mandatory feature for us.

## Proposition
A simple solution would be to add three new environment variables:
- `PYAPP_DISTRIBUTION_CPYTHON_REPOSITORY`
- `PYAPP_DISTRIBUTION_PYPY_HOST`
- `PYAPP_UV_REPOSITORY`

By default, they will keep the same url as before.
It's important to understand that we will keep the same download scheme. If we change the GitHub repository of [UV](https://github.com/astral-sh/uv) or [python-build-standalone](https://github.com/indygreg/python-build-standalone), we will still downloads the artifacts from the release section of the repository.

## Contribution

I worked on a pull-request and validated that the whole compilation & binary are working without any connectivity to GitHub when I set up the options.
I will link the pull-request to this issue.

### PR DESCRIPTION
**Pull request by Coruscant11**
Fixes #146 

I added also some tests ensuring the non-regression :slightly_smiling_face:

### CODE REVIEW

**Comment by Coruscant11** [comment]
I added our company to the Users page of the doc :smile:

**Comment by Coruscant11** [comment]
@ofek Hi!
Got the notification of the build :slightly_smiling_face: 

It seems the variables are not in the good order in the validate step:
```
PYAPP_UV_ONLY_BOOTSTRAP               | PYAPP_UV_REPOSITORY
PYAPP_UV_REPOSITORY                   | PYAPP_UV_ONLY_BOOTSTRAP
PYAPP_UV_VERSION                      | PYAPP_UV_VERSION
```

Any idea how to fix it? :thinking:

**Comment by ofek** [comment]
Thanks for this.

- It's alphabetical.
- Can we copy what was done for Hatch so that the backend doesn't matter? https://hatch.pypa.io/latest/how-to/python/custom/

**Comment by Coruscant11** [comment]
> * It's alphabetical.

Oh, makes sense! I will fix it, thanks. :laughing: 

> * Can we copy what was done for Hatch so that the backend doesn't matter? https://hatch.pypa.io/latest/how-to/python/custom/

You mean, adding the same fork/mirror feature to hatch ?
If yes, then yes of course! :slightly_smiling_face:

**Comment by Coruscant11** [comment]
I will clean few things in the changes, I will edit this message when it will be okay :slightly_smiling_face:

**Comment by ofek** [comment]
No I actually mean to copy the concept over here. Someone opened up a PR implementing this same solution (it's very logical) but then I thought about how it would play out in practice so I came up with that way https://github.com/pypa/hatch/pull/1455#issuecomment-2132322224

**Comment by Coruscant11** [comment]
> No I actually mean to copy the concept over here. Someone opened up a PR implementing this same solution (it's very logical) but then I thought about how it would play out in practice so I came up with that way [pypa/hatch#1455 (comment)](https://github.com/pypa/hatch/pull/1455#issuecomment-2132322224)

Oh, okay I see!
Yes of course, I will use this tomorrow then :slightly_smiling_face: 

Thanks for the suggestion!

**Comment by Coruscant11** [comment]
Hi @ofek, I upaded the PR.

Here is how it looks now:
image

Is this what you had in mind? :slightly_smiling_face:

**Comment by Coruscant11** [comment]
Updated the variable name to `PYAPP_DISTRIBUTION_SOURCE_<NAME>` in order to be consistent with other options names. I updated the doc too.

Have stuff to do, I will update very soon the doc for the UV customization.

**Comment by ofek** [comment]
At a glance this is exactly what I had in mind, thanks! I will take a look this weekend.

**Comment by Coruscant11** [comment]
Normally fixed the tests 🙂 

Also the updated environment variable name update:
image

Feel free to tell me if you want to change the name of `PYAPP_UV_CUSTOM_SOURCE`. Maybe just `PYAPP_UV_SOURCE` ? As you wish!

See you this weekend 😄 Take care

**Comment by ofek** [comment]
It looks like your branch doesn't allow pushes, I'm going to create a new branch with your commits https://github.com/ofek/pyapp/pull/152

**Comment by ofek** [comment]
Superseded by https://github.com/ofek/pyapp/pull/153

**Pull request closed without merging**
