### PR TITLE
Update to 20241206 releases of python-build-standalone.

### PR DESCRIPTION
**Pull request by kpfleming**

### CODE REVIEW

**Review by ofek — COMMENTED** [review]
Thanks! Do you mind also adding a release note?

**Comment by kpfleming** [comment]
Done! Also this was my first time running a Python script with embedded dependencies... and it just worked :-)

**Review by ofek — APPROVED** [review]
Thanks a lot!

**Comment by kpfleming** [comment]
Do you want to handle the update in Hatch, or should I attempt that?

**Comment by ofek** [comment]
I'll do that because master is not in a state conducive to releasing so I've been using a branch.

**Pull request merged**
