### PR TITLE
Fix distribution embeds and update docs

### LINKED ISSUE #79: Cannot use `PYAPP_DISTRIBUTION_PATH` (at least with locally embedded projects)
When embedding a local tar of a python distribution, I get the following error

```
  --- stderr
  thread 'main' panicked at build.rs:565:9:

  Unable to determine format for distribution source: 
```

(yes, `distribution_source` is an empty string, I checked).

This occurs when providing `PYAPP_PROJECT_PATH` (embedding a wheel), `PYAPP_DISTRIBUTION_PATH`, and `PYAPP_EXEC_SPEC`. Removing `PYAPP_DISTRIBUTION_PATH`, works but python is not bundled along with the binary.

I have an [example here](https://github.com/nmay231/pyapp_bug).

<details>

<summary>

full output of `make build-bugged`

</summary>

```
$ make build-bugged
poetry build -f wheel
Building pyapp-bug (0.1.0)
  - Building wheel
  - Built pyapp_bug-0.1.0-py3-none-any.whl
cd pyapp-latest && \
	PYAPP_PROJECT_PATH=../dist/pyapp_bug-0.1.0-py3-none-any.whl \
	PYAPP_DISTRIBUTION_PATH=./python-3.10.13.tar.gz \
	PYAPP_EXEC_SPEC=pyapp_bug.entry:main \
	cargo build --release
   Compiling pyapp v0.13.0 (/home/nmay/cur/pyapp_bug/pyapp-latest)
error: failed to run custom build command for `pyapp v0.13.0 (/home/nmay/cur/pyapp_bug/pyapp-latest)`

Caused by:
  process didn't exit successfully: `/home/nmay/cur/pyapp_bug/pyapp-latest/target/release/build/pyapp-fa2006654aeb24f9/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=PYAPP_PROJECT_DEPENDENCY_FILE=
  cargo:rustc-env=PYAPP__PROJECT_DEPENDENCY_FILE_NAME=
  cargo:rustc-env=PYAPP_PROJECT_NAME=pyapp-bug
  cargo:rustc-env=PYAPP_PROJECT_VERSION=0.1.0
  cargo:rustc-env=PYAPP__PROJECT_EMBED_FILE_NAME=pyapp_bug-0.1.0-py3-none-any.whl
  cargo:rustc-env=PYAPP_DISTRIBUTION_SOURCE=
  cargo:rustc-env=PYAPP__DISTRIBUTION_ID=12080488350626410958

  --- stderr
  thread 'main' panicked at build.rs:565:9:


  Unable to determine format for distribution source: 


  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:13: build-bugged] Error 101
```

</details>

### PR DESCRIPTION
**Pull request by nmay231**
Closes #79 

I updated the docs with what would have (hopefully) prevented any of my confusion.

### CODE REVIEW

**Comment by nmay231** [comment]
Hold on, this is broken. I thought I tested this change, but I must have been using the wrong one when doing so. The binary compiles fine with this change but doesn't run.

**Comment by nmay231** [comment]
I'm not exactly certain what the issue was before, but I haven't gotten it since I started deleting `~/.local/share/pyapp` and `~/.cache/pyapp` before each test install.

Changing the line to `local_path` does fix the main issue, except I also had to update `PYAPP_DISTRIBUTION_PYTHON_PATH` from `bin/python3` to `python/bin/python3` since that's how the standalone archives are arranged. Docs have been updated to reinforce that point.

**Comment by ofek** [comment]
I don't have time to review this today but can you please make sure the change is correct? I'm almost positive that the empty string is required to indicate that there is no source at runtime.

**Comment by nmay231** [comment]
Certainly!

During runtime, there is no check at all; it blindly tries downloading the source if no embed exists. During build-time, the behavior is identical to providing `PYAPP_DISTRIBUTION_SOURCE` and `PYAPP_DISTRIBUTION_EMBED` except that `PYAPP_DISTRIBUTION_PIP_AVAILABLE` gets set to true; that's a simple fix though. There is no other `.is_empty()` check that changes behavior.

To clarify what I should do, I need to know how you intend `PYAPP_DISTRIBUTION_PATH` to be used. Do you intend `*_PATH` to only be one of the standalone builds, or do you expect someone to zip their local python builds and package that? My personal usecase was to cache the download of the build(s) to allow faster iteration.

In any case, I think we should deprecate `*_PATH` and allow `*_SOURCE` to be a file. Then any branching on embed vs download would check if `*_SOURCE` is a url.

Sidenote: I remember why I got the error I was getting earlier.

> `Error: download failed: ../dist/python.tar.gz`

I was curling the tar file without `-L` and getting an empty file because of url redirects. [`distribution.rs:materialize`](https://github.com/ofek/pyapp/blob/cac431068972ea8cb415d16fbf7900c27d198947/src/distribution.rs#L128) then assumed since there was no embedding (empty file) that it has to download from a url.

**Comment by nmay231** [comment]
I updated to fix the issue with `PYAPP_DISTRIBUTION_PIP_AVAILABLE`.

The only issues that remain are:

- Do you want to deprecate `PYAPP_DISTRIBUTION_PATH`? (the reason why is explained above)
- How would we automatically test this and future changes?

You have the `test.yml` workflow that runs cowsay on a matrix of OSs and architectures, but that's obvisouly not enough on its own since this bug went unnoticed.

I could probably add tests, but I'm unfortunately no longer using pyapp for the project I'm working on right now so I'm less motivated to work on this contribution. However, I'll try not to leave this issue unresolved.

**Comment by ofek** [comment]
Thanks for your patience here! I'm about to push a change and merge this.

- Yes the option is intended for any prebuilt distribution as long as it's compressed with a known format.
- Currently, I don't want to deprecate the option because I like the explicitness of options for URLs vs paths. I'm open to changing my mind however.
- Testing is a good question! I honestly haven't had time to write proper tests so no worries, my bad.
- I'm going to remove the pip available change because it's possible that custom distributions that folks provide do not have pip already installed. I will update the documentation to make it more explicit that it would be a performance benefit in that case.

**Review by ofek — APPROVED** [review]
Thank you very much!

**Comment by ofek** [comment]
FYI I see what was happening and the pip available conditional you had there was indeed necessary so I added that back. I need more sleep... and to write tests lol

**Comment by nmay231** [comment]
Lol, we all could probably use a bit more sleep :)

**Pull request merged**
